twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/assets/img': images
    globals:
        website_domain: 'https://recettesenfolie.fr'

when@test:
    twig:
        strict_variables: true
